[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "oremi-core"
version = "2.1.2"
description = "The cornerstone of the Oremi ecosystem"
keywords = ["oremi", "core", "utils"]
authors = ["SÃ©bastien Demanou <demsking@gmail.com>"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://gitlab.com/demsking/oremi-core"
documentation = "https://gitlab.com/demsking/oremi-core/-/blob/main/README.md"
classifiers = [
  "Development Status :: 2 - Pre-Alpha",
  "Environment :: Console",
  "Intended Audience :: Developers",
  "Topic :: Software Development :: Libraries :: Python Modules",
  "Topic :: Software Development :: Localization",
  "License :: OSI Approved :: Apache Software License",
  "Operating System :: POSIX :: Linux",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
]

packages = [
  { include = "oremi_core" },
]

include = []

[tool.poetry.urls]
"Say Thanks!" = "https://www.buymeacoffee.com/demsking"
"Source" = "https://gitlab.com/demsking/oremi-core"
"Tracker" = "https://gitlab.com/demsking/oremi-core/-/issues"

[tool.poetry.dependencies]
python = ">=3.10,<4.0"
coloredlogs = "^15.0.1"
websockets = "^14.1"
python-dateutil = "^2.8.2"

[tool.poetry.group.dev.dependencies]
python-lsp-server = {extras = ["flake8", "pydocstyle", "pylint", "rope", "toml"], version = "^1.11.0"}

[tool.pytest.ini_options]
# Function starting with the following pattern are considered for test cases.
python_functions = "test_"

[tool.skjold]
sources = ["pyup", "gemnasium", "osv", "pypa"]
report_only = false # Exit with non-zero exit code on findings.
