# pyproject.toml
[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"
[project]
name = "Nigthanday_first_package"
version = "1.0.2"
description = "A simple CLI package but an amazing one."
dependencies = ["click==8.1.3"]
[project.scripts]
sub = "Nightanday_first_package.cli:cli"