[project]
authors = [
  {name = "Andrew Hoekstra", email = "andrew@pointevector.com"},
]
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3",
]
dependencies = []
description = "Add '.ðŸ' possible extensions."
license = "MIT"
name = "ext-snake"
readme = "README.md"
requires-python = ">=3.3"
version = "1.0.0"

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.hatch.build.targets.wheel]
only-include = ["src/ext/snake"]
sources = ["src"]

[tool.hatch.build.targets.wheel.force-include]
"resources" = "/"
