[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "slim_gym"
authors = [{name = "Niko Zuppas", email = "zuppas.3@osu.edu"}]
readme = "README.md"
dynamic = ["version", "description"]
dependencies = [
    "gymnasium==1.0.0",
    "matplotlib==3.10.0",
    "numpy==2.2.2",
]

[project.urls]
Home = "https://github.com/nzupp/SLiM-Gym"