[tool.poetry]
name = "akumaimageeffect"
version = "0.1.0"
description = "A Python project for image effects"
authors = ["akumanomi1988 <akumanomi1988@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
Pillow = "^8.0.0"

[tool.poetry.dev-dependencies]
pytest = "^6.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"