[project]
name = "samu"
version = "0.1.2"
description = "A simple coplanar electrical channel crosstalk extractor for Samuel."
authors = [
    { name = "Diogo Andre", email = "ddias@tudelft.nl" }
]
license = { file = "LICENSE" }
dependencies = [
    "click",
    "numpy",
    "scipy",
    "pydantic",
    "pydantic_yaml",
    "matplotlib",
    "rich",
    "pyyaml",
    "pyspice",
    "ruff"
]
readme = "README.md"
requires-python = ">=3.7"

[project.urls]
Homepage = "https://github.com/das-dias/samu"
Repository = "https://github.com/das-dias/samu.git"

[project.scripts]
samu = "samu:cli"

[tool.setuptools]
packages = ["src"]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
