[tool.poetry]
name = "restack_ai"
version = "0.0.56"
description = "Restack AI library"
authors = [
    "Restack Team <service@restack.io>"
]
readme = "README.md"
packages = [{include = "restack_ai", from = "."}]
include = ["restack_ai/py.typed"]

[tool.poetry.dependencies]
python = "^3.9"
colorama = "^0.4.6"
asyncio = "^3.4.3"
aiohttp = "^3.11.10"
msgspec = "^0.18.6"
temporalio = "^1.9.0"
pydantic = "^2.10.6"
python-dotenv = "^1.0.1"

[tool.poetry.group.dev.dependencies]
pytest = "^6.2"
flake8 = "^4.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
test = "restack_ai.test_connection:run_test"
