[project]
name = "polars-ls"
version = "0.1.0"
description = "List directory contents as Polars DataFrames"
readme = "README.md"
authors = [
    { name = "Louis Maddox", email = "louismmx@gmail.com" },
]
requires-python = ">=3.12"
dependencies = [
    "argh>=0.31.3",
]

[project.scripts]
pols = "pols:cli.cli"

[build-system]
requires = [
    "pdm-backend",
]
build-backend = "pdm.backend"

[dependency-groups]
dev = [
    "freezegun>=1.5.1",
    "inline-snapshot[black]>=0.19.3",
    "pytest>=8.3.4",
]

[tool]
