[tool.poetry]
name = "census_backup"
version = "0.1.1"
description = "Backup utilities."
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
censusdis = "^1.3.3"
logargparser = "^0.1.1"

[tool.poetry.group.lint.dependencies]
ruff = "^0.1.14"
flake8 = "^7.0.0"
black = {extras = ["jupyter"], version = "^24.1.0"}
isort = "^5.10.1"
pylint = "^2.15.2"
mypy = "^0.971"
types-requests = "^2.28.10"

[tool.poetry.scripts]
census-backup = "backup:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
