[build-system]
requires = ["flit_core>=3.4"]
build-backend = "flit_core.buildapi"


[project]
name = "kicad_auto_lib"
version = "0.0.2"
authors = [
  { name="Charles H. Gayot", email="charles@stepupsolutions.dk" },
]
description = "Fully automated library management in Kicad. Don't open the Manage Symbol/Footprint Libraries ever again."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "License :: OSI Approved :: GNU Affero General Public License v3",
]
license = { text = "AGPLv3" }
# license-files = ["LICENSE"]


# Add dependencies
dependencies = [
    "watchdog>=6.0.0",
    "sexpdata>=1.0.2",
]

[project.scripts]
kicad_auto_lib = "kicad_auto_lib:main"

# Add URLs
[project.urls]
Homepage = "https://github.com/StepUp-Solutions/kicad_auto_lib"
Issues = "https://github.com/StepUp-Solutions/kicad_auto_lib/issues"

# Include additional files
[tool.flit.sdist]
include = [
    "kicad_auto_lib.py",
    "LICENSE",
    "README.md",
    "*.py",  # Include all Python files in the same directory
]