[build-system]
requires = ["setuptools", "twine"]
build-backend = "setuptools.build_meta"

[project]
name = "BmpLib_Ai"
version = "0.0.25"
authors = [
  { name = "OUEDRAOGO Taoufiq", email = "taoufiq.ouedraogo@icloud.com" }
]
dynamic = ["dependencies", "optional-dependencies"]

description = "This package implements all the logic of Brief My Press.AI"
readme = "README.md"
requires-python = ">=3.10, <3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = { file = "LICENSE" }

[project.urls]
Homepage = "https://github.com/Taoufiq-Ouedraogo/Brief-My-Press-AI-Library"

[tool.setuptools.packages.find]
where = ["src"]
include = ["BmpLib_Ai"]
exclude = [".env", "env", ".gitignore", "*.ipynb", "src/BmpLib_Ai/__pycache__"]

[tool.setuptools.dynamic]
dependencies = { file = ["requirements.txt"] }