[tool.poetry]
name = "findly.unified-reporting-sdk"
version = "0.7.7"
license = "GPL-3.0-only"
description = ""
authors = []
readme = "README.md"
packages = [
    { include = "findly" },
]
include = [
    "findly/unified_reporting_sdk/protos/*",
]

[tool.poetry.dependencies]
python = "^3.9"
pandas = "^2.2.3"
protobuf = "^4.25.3"
backoff = "^2.2.1"
aiocache = "^0.12.2"
facebook-business = "^21.0.5"
sqlglot = "^25.25.1"
google-analytics-admin = "^0.22.7"
google-analytics-data = "^0.18.8"
google-api-python-client = "^2.122.0"
oauth2client = "^4.1.3"

[tool.poetry.group.typing.dependencies]
mypy = "^1.3.0"
types-python-dateutil = "^2.8.19.20240106"
types-protobuf = "^4.24.0.20240302"

[tool.poetry.group.dev.dependencies]
pytest = "^8.1.1"
pytest-asyncio = "^0.23.5.post1"
mypy-protobuf = "^3.5.0"
python-dotenv = "^1.0.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
ignore_missing_imports = "True"
disallow_incomplete_defs = "True"
check_untyped_defs = "True"
disallow_untyped_defs = "True"
warn_unused_ignores = "True"
exclude = ["protos"]

[tool.pytest.ini_options]
pythonpath = [
  "."
]
markers = [
    "manual: should only be ran manually",
]
addopts = "-m \"not manual\""
