[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "local-operator"
version = "0.0.28"
description = "A Python-based agent for local command execution"
readme = "README.md"
authors = [{ name = "Damian Tran", email = "damianvtran@gmail.com" }]
license = { file = "LICENSE" }
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.12",
]
keywords = ["local", "agent", "execution", "operator"]
dependencies = [
    "langchain-openai",
    "langchain-ollama", 
    "langchain-anthropic",
    "langchain",
    "python-dotenv",
    "pydantic",
    "tiktoken",
]
requires-python = ">=3.12"

[project.optional-dependencies]
dev = ["black", "isort", "pylint", "pyright", "pytest", "pytest-asyncio"]

[project.urls]
Homepage = "https://github.com/damianvtran/local-operator"

[project.scripts]
local-operator = "local_operator.cli:main"

[tool.black]
line-length = 100
target-version = ['py312']

[tool.pylint."messages control"]
ignore = ["setup.py", "__init__.py"]
disable = "all"
enable = [
    "empty-docstring",
    "missing-class-docstring",
    "missing-function-docstring",
    "missing-module-docstring"
]

[tool.isort]
profile = "black"

[tool.pyright]
reportMissingTypeArgument = true
strictListInference = true
reportPrivateImportUsage = false

[tool.pytest.ini_options]
addopts = "-v -s"
testpaths = ["tests"]
