[build-system]
requires = ["hatchling","pyinstaller"]
build-backend = "hatchling.build"

[project]
name = "aamg"
version = "1.0.9"
authors = [
  { name="WeDu-official", email="fplu.the.founder@gmail.com" },
]

description = "THE Advanced Application Manager Generator or AAMG is a Python library for creating AAMs from A to Z using Python."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Development Status :: 6 - Mature",
    "Intended Audience :: Developers",
    "Natural Language :: English",
    "Operating System :: Microsoft :: Windows :: Windows 8.1",
    "Operating System :: Microsoft :: Windows :: Windows 10",
    "Operating System :: Microsoft :: Windows :: Windows 11",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "License :: Other/Proprietary License"
]

[project.urls]
Homepage = "https://github.com/WeDu-official/AAMG"
Issues = "https://github.com/WeDu-official/AAMG/issues"

[tool.hatch.build.targets.wheel]
packages = ["src/aamg/aamg.py"]