[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pymsh"
version = "1.2.2"
authors = [
  { name="Carlton Shepherd", email="carlton@linux.com" },
]

keywords = ["hashing", "hash", "cryptography", "multi-set", "multiset", "crypto", "security"]
description = "The Python multiset hashing library"
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.7"
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Topic :: Security :: Cryptography"
]

[project.urls]
"Homepage" = "https://github.com/cgshep/pymsh"
"Issues" = "https://github.com/cgshep/pymsh/issues"

[project.optional-dependencies]
test = ["pytest", "mypy"]
