[package]
name = "pyaxp"
version = "0.1.0"
edition = "2021"

[dependencies]
pyo3 = { version = "0.23.3", features = ["extension-module", "serde"] }
yaxp-common = { path = "../yaxp-common" }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"


[lib]
name = "pyaxp"
crate-type = ["cdylib", "rlib"]
