[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "unichat"
version = "3.3.1"
authors = [
    { name = "Stefan", email = "versed_info0w@icloud.com" },
]
description = "Universal API chat Python client for OpenAI, MistralAI, Anthropic, xAI, Google AI and DeepSeek."
readme = "README.md"
requires-python = ">=3.6"
license = {file = "LICENSE"}
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "anthropic~=0.45.2",
    "mistralai~=1.5.0",
    "openai~=1.61.0",
]

[project.urls]
Repository = "https://github.com/amidabuddha/unichat"