[tool.poetry]
name = "stpstone"
version = "1.0.0"
description = ""
authors = ["guilhermegor <guirodrigues.gor@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.12,<4.0"
workalendar = "15.0.1"
pytz = "2024.1"
python-dateutil = "2.8.2"
more-itertools = "9.1.0"
businesstimedelta = "1.0.1"
pandas = "2.1.2"
pathlib = "1.0.1"
numpy = ">=1.26.0,<2.0.0"
seaborn = "0.11.1"
statsmodels = "0.14.1"
sklearn = "0.0"
boto3 = "1.35.68"
keyring = "24.3.1"
pycurl = "7.45.3"
wget = "3.2"
requests = "2.31.0"
py7zr = "0.16.2"
validate-docbr = "1.10.0"
pynubank = "2.17.0"
asyncio = "3.4.3"
bolsa = "2.0.0"
investpy = "1.0.3"
yfinance = "0.1.70"
yahooquery = "2.3.2"
nelson-siegel-svensson = "0.4.2"
cvxopt = "1.3.0"
plotly = "5.14.1"
bs4 = "0.0.1"
numpy-financial = "1.0.0"
urllib3 = "1.26.3"
lxml = "4.9.3"
selenium = "3.141.0"
joblib = "1.4.2"
tabula = "1.0.5"
pypdf2 = "1.27.5"
fpdf = "1.7.2"
ftfy = "6.1.3"
basicauth = "0.4.1"
unidecode = "1.2.0"
pywin32 = {version = "300", platform = "win32"}
xlwt = "1.3.0"
pymsteams = "0.1.14"
typing = "3.7.4.3"
pyyaml = "5.3.1"
pyodbc = "4.0.35"
psycopg2 = "2.8.6"
sqlalchemy = "1.4.52"
sympy = "1.9"
mlxtend = "0.23.1"
statistics = "1.0.3.5"
sendgrid = "6.11.0"
slack = "0.0.2"
typeform = "1.1.0"
pymysql = "1.1.1"
pytest = "^7.0"


[tool.poetry.group.dev.dependencies]
pre-commit = "^4.0.1"
pygments = "2.19.1"
twine = "^6.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
