[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "local-aws-lambda"
version = "0.1.3"
authors = [
    {name = "Aswath", email = "your.email@example.com"}
]
description = "A package to simulate AWS Lambda locally."
readme = "README.md"
requires-python = ">=3.7"
dependencies = []

[project.scripts]
local-lambda = "local_lambda.cli:main"

[project.urls]
"Homepage" = "https://github.com/yourusername/local-aws-lambda"
"Bug Tracker" = "https://github.com/yourusername/local-aws-lambda/issues"
