[project]
name = "scipy-events"
description = "A library of events for scipy.integrate.solve_ivp."
version = "0.4.2"
authors = [{ name = "Mauro Silberberg", email = "maurosilber@gmail.com" }]
readme = "README.md"
license = "MIT"
classifiers = ["Programming Language :: Python :: 3"]
requires-python = ">=3.10"
dependencies = ["numpy", "scipy"]

[project.urls]
homepage = "https://github.com/maurosilber/scipy-events"
issues = "https://github.com/maurosilber/scipy-events/issues"
changelog = "https://github.com/maurosilber/scipy-events/blob/main/CHANGELOG.md"
documentation = "https://maurosilber.github.io/scipy-events"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
cache-keys = [{ file = "pyproject.toml" }, { git = true }]

[tool.pytest.ini_options]
addopts = "--import-mode=importlib"
pythonpath = "."

[tool.ruff.format]
docstring-code-format = true

[tool.ruff.lint]
extend-select = ["I"]

[tool.pyright]
typeCheckingMode = "standard"
venv = "test"
venvPath = ".pixi/envs/"

[tool.pixi.project]
channels = ["https://fast.prefix.dev/conda-forge"]
platforms = ['osx-arm64', 'linux-64']

[tool.pixi.tasks]
release = "git tag $(pixi project version get) && git push && git push --tags || echo 'Run: pixi project version <major|minor|patch>'"

[tool.pixi.dependencies]
python = ">=3.10"

[tool.pixi.environments]
lint = { features = ["lint"], no-default-feature = true }
build = { features = ["build"], no-default-feature = true }
test = { features = ["test"], solve-group = "default" }
test-py310 = ["test", "py310"]
test-py311 = ["test", "py311"]
test-py312 = ["test", "py312"]
test-py313 = ["test", "py313"]

[tool.pixi.feature.lint.dependencies]
pre-commit = "*"
pre-commit-hooks = "*"
taplo = "*"
ruff = "*"
mdformat = "*"
mdformat-ruff = "*"
pyright = "*"

[tool.pixi.feature.lint.tasks]
pre-commit-install = "pre-commit install"
lint = "pre-commit run"

[tool.pixi.feature.build.dependencies]
python = "*"
uv = "*"

[tool.pixi.feature.build.pypi-dependencies]
mdremotifier = ">=0.5.0"

[tool.pixi.feature.build.tasks]
build = { cmd = "uv build", depends-on = ["remotify"] }
publish = "uv publish"
remotify = { cmd = [
  "mdremotifier",
  "-i",
  "README.md",
  "-o",
  "README.md",
  "--url-prefix",
  "https://github.com/maurosilber/scipy-events/blob/main",
  "--img-url-prefix",
  "https://raw.githubusercontent.com/maurosilber/scipy-events/refs/heads/main/",
] }

[tool.pixi.feature.test.dependencies]
pytest = "*"
tqdm = ">=4.67.1,<5"

[tool.pixi.feature.test.pypi-dependencies]
scipy-events = { path = ".", editable = true }
pytest-readme = ">=1.0.1,<2"

[tool.pixi.feature.test.tasks]
test = "pytest --doctest-modules"

[tool.pixi.feature.py310.dependencies]
python = "3.10.*"

[tool.pixi.feature.py311.dependencies]
python = "3.11.*"

[tool.pixi.feature.py312.dependencies]
python = "3.12.*"

[tool.pixi.feature.py313.dependencies]
python = "3.13.*"
