[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "json_js"
version = "0.1.5"
dependencies = []

[tool.setuptools.packages.find]
where = ["src"]
