[tool.poetry]
name = "salesanalyzer_mds"
version = "2.1.0"
description = "A Python package for sales forecasting, statistical analysis, and data-driven insights"
authors = ["Daria Khon, Franklin Aryee, Yeji Sohn"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10"
scikit-learn = ">=1.6.1"
pandas = ">=2.2.3"


[tool.poetry.group.dev.dependencies]
pytest = ">=8.3.4"
jupyter = ">=1.1.1"
myst-nb = ">=1.1.2"
sphinx-autoapi = ">=3.4.0"
sphinx-rtd-theme = ">=3.0.2"
pytest-cov = ">=6.0.0"
python-semantic-release = {version = "^9.17.0", python = "^3.12"}

[tool.semantic_release]
version_toml = [
    "pyproject.toml:tool.poetry.version",
]                                                     # version location
branch = "main"                                       # branch to make releases of
changelog_file = "CHANGELOG.md"                       # changelog file
build_command = "pip install poetry && poetry build"  # build dists    

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
