[tool.poetry]
name = "goose-py"
version = "0.3.12"
description = "A tool for AI workflows based on human-computer collaboration and structured output."
authors = [
    "Nash Taylor <nash@chelle.ai>",
    "Joshua Cook <joshua@chelle.ai>",
    "Michael Sankur <michael@chelle.ai>"
]
readme = "README.md"
homepage = "https://github.com/chelle-ai/goose"
repository = "https://github.com/chelle-ai/goose"
documentation = "https://github.com/chelle-ai/goose"
keywords = ["ai", "yaml", "configuration", "llm"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
]
packages = [
    { include = "goose" }
]


[tool.poetry.dependencies]
python = "^3.12"

jsonpath-ng = "^1.7.0"
litellm = "^1.56.5"
pydantic = "^2.8.2"
ipykernel = { version = "*", optional = true }
pytest = { version = "<8", optional = true }
pytest-mock = { version = "*", optional = true }
pytest-asyncio = { version = "*", optional = true }


[tool.poetry.extras]
test = ["ipykernel", "pytest", "pytest-mock", "pytest-asyncio"]


[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning>=1.0.0"]
build-backend = "poetry_dynamic_versioning.backend"

[tool.pyright]
pythonVersion = "3.12"
typeCheckingMode = "strict"
reportMissingModuleSource = false
useLibraryCodeForTypes = false
reportImportCycles = false
reportUnknownMemberType = false
reportUnknownVariableType = false
stubPath = ".stubs"

[tool.pytest.ini_options]
filterwarnings = [
    "ignore::DeprecationWarning",
    "ignore::SyntaxWarning",
    "ignore::UserWarning",
]
