[package]
name = "procol"
version = "0.1.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "procol"
crate-type = ["cdylib", "lib"]

[dependencies]
pyo3 = { version = "0.23.3", features = ["extension-module"] }
itertools = "0.10.1"
