[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "json-js"
version = "0.1.0"
description = "Python JSON like JavaScript"
authors = [{name = "Fabio Antonio Astore", email = "astore.a.fabio@gmail.com"}]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.13"

[project-urls]
Homepage = ""
Issues = ""
