[project]
name = "edalite"
version = "0.5.0"
description = ""
authors = [
    {name = "hyeonho cho",email = "111675679+aesthetics-of-record@users.noreply.github.com"}
]
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "nats-py (>=2.9.0,<3.0.0)",
    "redis[hiredis] (>=5.2.1,<6.0.0)"
]

[tool.poetry]
packages = [{include = "edalite"}]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
