[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "perplexity-mcp-server"
version = "0.2.2"
requires-python = ">=3.11"
readme = "README.md"
description = "Perplexity MCP Server"
dependencies = [
    "aiohttp",
    "pydantic",
    "mcp>=1.0.2",
]

[project.scripts]
perplexity-mcp-server = "perplexity_mcp.run:main"

[tool.hatch.build.targets.wheel]
packages = ["src/perplexity_mcp"]

[tool.hatch.metadata]
allow-direct-references = true