[login]
"Please Login Again"="Please Login Again"
"User is not active"="User is not active"
"User Does Not Exists"="User Does Not Exists"
"Please Login First"="Please Login First"
"User or Password error"="User or Password error"
"User Not Log In"="User Not Log In"
"Get Permission List"="Get Permission List"

[permission]
"Get User List"="Get User List"
"Create One User"="Create One User"
"Set Permission For User"="Set Permission For User"
"Change Password"="Change Password"
"Lock & Unlock User"="Lock & Unlock User"
"Delete One User"="Delete One User"

[detail]
"User exists"="User exists"
"User not exists"="User not exists"
"User does not have permission to create user"="User does not have permission to create user"
"Can not change admin's permision"="Can not change admin's permision"
"Can not change your own permission"="Can not change your own permission"
"User does not have permission to set permission for user"="User does not have permission to set permission for user"
"User does not have permission to change password"="User does not have permission to change password"
"User can only change your own password"="User can only change your own password"
"Can not lock admin"="Can not lock admin"
"User does not have permission to lock user"="User does not have permission to lock user"
"User can not lock/unlock your own"="User can not lock/unlock your own"
"Can not delete admin"="Can not delete admin"
"User does not have permission to delete user"="User does not have permission to delete user"
"User can not delete your own"="User can not delete your own"

[msg]
"Success Create User"="Success Create User"
"Success Change User Permission"="Success Change User Permission"
"Success Change Password"="Success Change Password"
"Success lock User"="Success lock User"
"Success unlock User"="Success unlock User"
"Success delete User"="Success delete User"

[others]
"Success Login"="Success Login"
"Welcome Back Again"="Welcome Back Again"