[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pathshandler"
version = "0.0.1"
authors = [
  { name="Gauthier Patin", email="g.patin@monemail.com" },
]
dynamic = ['readme']
description = "Package to manipulate microfading data"
requires-python = ">=3.8"
license = {file = "LICENSE"} 
keywords = ["paths", "folders"]
classifiers = [
    "Programming Language :: Python :: 3", 
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",   
    "Operating System :: OS Independent",
]


[project.urls]
Homepage = "https://github.com/g-patin/pathshandler"


[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
pathshandler = ['*.json', '*.png']

