[tool.poetry]
name = "pynewsml"
version = "0.1.0"
description = "A NewsML parsing library"
authors = ["Jos√© Coelho <16445494+jcoelho93@users.noreply.github.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
lxml = "^5.3.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
