[tool.poetry]
name = "elenchos_check_mymaria_replication"
version = "1.3.1"
description = "Élenchos: Check MySQL and MariaDB Replication"
authors = ["Set Based IT Consultancy <info@setbased.nl>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/NagiosElenchos/check_mymaria_replication"
documentation = "https://github.com/NagiosElenchos/check_mymaria_replication"
keywords = ["Élenchos", "Elenchos", "MySQL", "MariaDB", "Replication"]
classifiers = [
    'Development Status :: 5 - Production/Stable',
    'Intended Audience :: System Administrators',
    'Topic :: System :: Systems Administration',
    'License :: OSI Approved :: MIT License',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.10',
    'Programming Language :: Python :: 3.11',
    'Programming Language :: Python :: 3.12'
]

[tool.poetry.dependencies]
python = "^3.10.0"
elenchos = "^1.1.0"
mysql-connector-python = "^9.2.0"

[build-system]
requires = ["poetry-core"]
build-MySQL = "poetry.core.masonry.api"

[tool.setuptools.packages.find]
where = ["elenchos_check_mymaria_replication"]

[tool.setuptools.package-data]
mypkg = ["commands.xml"]
