[project]
name = "conceptnet_local"
version = "1.0.1"
authors = [
  { name="Lukas Mautner", email="lukas.mautner98@gmail.com" },
]
description = "ConceptNet and embeddings with a local DB and API."
readme = "README.md"
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "numpy",
    "pydantic",
    "sortedcontainers",
    "python-dotenv",
    "inflect",
    "nltk",
]

[project.optional-dependencies]
dev = [
    "black"
]

[project.urls]
Homepage = "https://github.com/lukDev/conceptnet-local"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
license-files = ["LICENSE"]

[tool.black]
line-length = 100

[tool.ruff]
line-length = 100
exclude = ["tests"]

[tool.ruff.lint]
select = ["D", "E", "F", "W", "S", "PL", "N"]
fixable = ["ALL"]
ignore = ["D100", "D101", "D104", "D107", "D203", "D212", "E501", "S608"]
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.isort]
profile = "black"

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]