[tool.poetry]
name = "dsci_524_ezplot"
version = "0.0.5"
description = "A Python package for enhanced data visualization"
authors = ["Daduica Julian, Elshaday Yoseph, Henry(Mu) Ha, Zhou Yining"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11"
matplotlib = ">=3.10.0"
pandas = ">=2.2.3"
seaborn = "^0.13.2"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.4"
pytest-cov = "^6.0.0"
pytest-mpl = "^0.17.0"
sphinx-autoapi = "^3.4.0"
sphinx-rtd-theme = "^3.0.2"
myst-nb = {version = "^1.1.2", python = "^3.11"}

[tool.semantic_release]
version_toml = [
    "pyproject.toml:tool.poetry.version",
]                                                    # version location
branch = "main"                                      # branch to make releases of
changelog_file = "CHANGELOG.md"                      # changelog file
build_command = "pip install poetry && poetry build" # build dists 

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
