[project]
name = "django-runprod"
version = "0.1.1"
description = "Django management command to run WSGI server for production. Also support serving static files through WhiteNoise."
readme = "README.md"
authors = [
    { name = "kamal", email = "kamal@koditi.my" }
]
requires-python = ">=3.10"
dependencies = [
    "gunicorn>=23.0.0",
    "sentry-sdk>=2.20.0",
    "whitenoise>=6.8.2",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
