[project]
name = "dashai_test_classification_package"
version = "0.0.7"

dependencies = [
    'torchvision == 0.14.0',
    'dashai_test_classification_metrics_plugin',
]

authors = [
  { name="DashAI team" },
  { email="dashaisoftware@gmail.com" },
]

keywords = [
    "DashAI",
    "Model",
    "Task",
    "Dataloader",
]

description = "Image Classification Plugin for DashAI"
readme = "README.md"
requires-python = ">=3.8"

[project.entry-points.'dashai.plugins']
imageClassificationTask = 'dashai_test_image_classification_plugin.image_classification_task:ImageClassificationTask'
MLPClassifierModel = 'dashai_test_image_classification_plugin.mlp_image_classifier:MLPImageClassifier'
imageDataloader = 'dashai_test_image_classification_plugin.image_dataloader:ImageDataloader'

[project.urls]
Homepage = "https://github.com/DashAISoftware/DashAI"
Issues = "https://github.com/DashAISoftware/DashAI/issues"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"